### PR TITLE
throw fatal error if send sdp answer failed

### PR DESCRIPTION
**Pull request by LiangFang001**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ycyang1229** [comment]
@LiangFang001 Can you point out where to invoke pc_throwFatalError?

**Comment by LiangFang001** [comment]
> @LiangFang001 Can you point out where to invoke pc_throwFatalError?
@ycyang1229 
Hi,
you can refer to this pr:
https://github.com/awsblake/AmebaPro2_v9.2b_SDK/pull/7/files#diff-c0186358e689254d8a2729617963cfceae919335f74ebab0813967b3d7673af4

**Comment by ycyang1229** [comment]
> > @LiangFang001 Can you point out where to invoke pc_throwFatalError?
> > @ycyang1229
> > Hi,
> > you can refer to this pr:
> > https://github.com/awsblake/AmebaPro2_v9.2b_SDK/pull/7/files#diff-c0186358e689254d8a2729617963cfceae919335f74ebab0813967b3d7673af4

I can not open the link. However, please merge the code of invoking pc_throwFatalError into this pr?

**Comment by LiangFang001** [comment]
@ycyang1229 
Hi,
This PR link has been changed  to:
https://github.com/HungTseLee/amazon-kinesis-video-streams-webrtc-sdk-c/pull/11

**Pull request closed without merging**
